name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Capture dependency graph information in environment variables
    - name: Capture dependency graph info
      id: capture_dependency_info
      run: |
        echo "DEPENDENCY_GRAPH_URL=https://api.github.com/repos/$GITHUB_REPOSITORY/dependency-graph/snapshots/$GITHUB_RUN_ID" >> $GITHUB_ENV
        echo "DEPENDENCY_GRAPH_AUTH_TOKEN=$GITHUB_TOKEN" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Optional: Use the captured information in your workflow as needed
    - name: Update dependency graph
      run: |
        echo "Updating dependency graph using URL: $DEPENDENCY_GRAPH_URL"
        # Use the $DEPENDENCY_GRAPH_AUTH_TOKEN and $DEPENDENCY_GRAPH_URL as needed
        # For example, make HTTP requests or perform other actions here
      env:
        DEPENDENCY_GRAPH_URL: ${{ steps.capture_dependency_info.outputs.DEPENDENCY_GRAPH_URL }}
        DEPENDENCY_GRAPH_AUTH_TOKEN: ${{ steps.capture_dependency_info.outputs.DEPENDENCY_GRAPH_AUTH_TOKEN }}
